### ISSUE TITLE
Color mismatch between main window and bdv

### ISSUE THREAD

**Issue by vzinche** [platybrowser/platybrowser-fiji#49]
![Screenshot from 2020-02-07 16-02-54](https://user-images.githubusercontent.com/32451366/74045244-b2320500-49cc-11ea-89e6-aabc86c8dd68.png)

**Comment by tischi** [comment]
@constantinpape

The reason is that we got rid of the `mask` modality, which is a segmentation with only one object.
Right now something is implicitly a `mask` if it is a `segmentation` and if there is no associated table and if there is no `ColorMap` but only a single `Color` (as below).

```
"prospr-6dpf-1-whole-segmented-foregut": {
    "Color": "Magenta",
    "MaxValue": 1000,
    "MinValue": 0,
    "Storage": {
      "local": "local/prospr-6dpf-1-whole-segmented-foregut.xml"
    }
  },
```

Maybe we should add an explicit "Modality" filed in the json...
Could we quickly **meet Monday morning ~10:00** to discuss?

**Comment by constantinpape** [comment]
> Maybe we should add an explicit "Modality" filed in the json...
> Could we quickly **meet Monday morning ~10:00** to discuss?

10 works for me. Do you pass by then?
